name: "Release from tag"

on:
  push:
    tags:
      - "v*"

jobs:
  gh_tagged_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease


    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          pddl-planning/build/outputs/aar/*.aar
          pddl-planning-test/build/outputs/aar/*.aar
      id: "automatic_releases"

